service: python-builds

plugins:
  - serverless-python-requirements
  - serverless-step-functions
  - serverless-pseudo-parameters
custom: ${file(./serverless-custom.yml)}

package:
  exclude:
    - integration/**
    - builder/**
    - docs/**
    - node_modules/**

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  deploymentBucket:
    name: ${self:custom.deploymentBucket}
  stackTags: ${self:custom.${self:provider.stage}.stackTags}
  iamRoleStatements:
    -  Effect: Allow
       Action:
         - "batch:*"
       Resource: '*'
    -  Effect: Allow
       Action:
         - "s3:*"
       Resource:
        - arn:aws:s3:::${self:custom.${self:provider.stage}.s3Bucket}
        - arn:aws:s3:::${self:custom.${self:provider.stage}.s3Bucket}/*
  environment:
    S3_BUCKET: ${self:custom.${self:provider.stage}.s3Bucket}
    JOB_QUEUE_ARN:
      Ref: pythonBuildsBatchJobQueue
    JOB_DEFINITION_ARN_ubuntu_1804:
      Ref: pythonBuildsBatchJobDefinitionUbuntu1804
    JOB_DEFINITION_ARN_ubuntu_2004:
      Ref: pythonBuildsBatchJobDefinitionUbuntu2004
    JOB_DEFINITION_ARN_ubuntu_2204:
      Ref: pythonBuildsBatchJobDefinitionUbuntu2204
    JOB_DEFINITION_ARN_centos_7:
      Ref: pythonBuildsBatchJobDefinitionCentos7
    JOB_DEFINITION_ARN_centos_8:
      Ref: pythonBuildsBatchJobDefinitionCentos8
    JOB_DEFINITION_ARN_opensuse_42:
      Ref: pythonBuildsBatchJobDefinitionOpensuse42
    JOB_DEFINITION_ARN_opensuse_153:
      Ref: pythonBuildsBatchJobDefinitionOpensuse153
    SUPPORTED_PLATFORMS: ubuntu-1804,ubuntu-2004,ubuntu-2204,centos-7,centos-8,opensuse-42,opensuse-153

functions:
  queueBuilds:
    timeout: 30
    handler: handler.queue_builds
  jobQueueStatus:
    handler: handler.poll_running_jobs


stepFunctions:
  stateMachines: ${file(./serverless-stepf.yml)}

resources:
  Resources: ${file(./serverless-resources.yml)}
